name: Release
on:
  push:
    branches: [ main, next, beta ]
  pull_request:
    branches: [ main, next, beta ]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [17]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 7.0.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build package
      run: pnpm build
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: cd ./packages/rapid-form && npx semantic-release
